language: node_js
sudo: false

node_js:
  - "7"

cache:
  directories:
    - node_modules
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

# Make chrome browser available for testing
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - COVERAGE=true npm run test
  - ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info
  - npm run build

env:
  - CXX=g++-4.8
